name: CI commit action

on:
  push:
    branches-ignore: [ 'gh-pages' ]

  pull_request:
    branches-ignore: [ 'gh-pages' ]

jobs:
  build:
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ '20.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install dependencies
        run: npm install; 
      - run: npm install --global grunt webpack karma webpack-cli typescript typedoc;
      - run: npm run test; 
      - run: npm run build:prod;
      - run: npm run build:docs;
  
      - name: Generate documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs
